org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# Projetinho mansao
mod_id=sentosaiyanaddon
mod_name=DragonMine Z: Sento Saiyan Race!
mod_version=1.0.1
mod_group_id=com.WhyNotKuroshi.dmz_sentosaiyan_addon
mod_author=WhyNotKuroshi
mod_authors=WhyNotKuroshi
mod_description=Adds the Sento Saiyan race to DragonMineZ.